name: Build and publish container image

on:
  push:
    branches:
      - main

env:
  TAG_NAME: regolint:${{ github.sha }}
  GITHUB_IMAGE_REPO: ghcr.io/${{ github.repository_owner }}/regolint
  GITHUB_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/regolint:${{ github.sha }}
  GITHUB_IMAGE_LATEST: ghcr.io/${{ github.repository_owner }}/regolint:latest

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        run: docker build . -t ${{ env.GITHUB_IMAGE_LATEST }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: docker push ${{ env.GITHUB_IMAGE_LATEST }}
      - name: Rename image (commit ID)
        run: docker tag ${{ env.GITHUB_IMAGE_LATEST }} ${{ env.GITHUB_IMAGE_NAME }}
      - name: Push image
        run: docker push ${{ env.GITHUB_IMAGE_NAME }}
      - uses: actions/checkout@v2
